name = "aiken-lang/stdlib"
version = "main"
compiler = "v1.1.4"
plutus = "v3"
description = "The Aiken Standard Library"

[repository]
user = "aiken-lang"
project = "stdlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"
