name = "aiken-lang/stdlib"
version = "main"
compiler = "v1.1.2"
plutus = "v3"
description = "The Aiken Standard Library"

[repository]
user = "aiken-lang"
project = "stdlib"
platform = "github"

dependencies = []

[config]
